### ISSUE TITLE
Error execution

### ISSUE THREAD

**Issue by tXambe** [n00py/LAPSDumper#2]
Hello,

when I run the script I have this error:

```
 sudo python3 laps.py -u usr01 -p pass123  -d local.com -l DC01.local.com
Traceback (most recent call last):
  File "/opt/CRACK-PASSWD/LAPSDumper/laps.py", line 31, in <module>
    main()
  File "/opt/CRACK-PASSWD/LAPSDumper/laps.py", line 25, in main
    c = Connection(s, user=args.domain + "\\" + args.username, password=args.password, authentication=NTLM, auto_bind=True)
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 356, in __init__
    self._do_auto_bind()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 380, in _do_auto_bind
    self.open(read_server_info=False)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 153, in open
    raise LDAPSocketOpenError('invalid server address')
ldap3.core.exceptions.LDAPSocketOpenError: invalid server address


```

A greeting and thanks

**Comment by TheMuntu** [comment]
I have the same issue here and haven't yet found how to solve it 😓

**Comment by n00py** [comment]
nmap DC01.local.com -p 389 and validate the output

**Comment by TheMuntu** [comment]
> nmap DC01.local.com -p 389 and validate the output

nmap failed to resolve the host while other tools can resolve it without problems.

**Comment by n00py** [comment]
Well sounds like its a DNS issue.  But regardless I think you should be able to use an IP address for the -l parameter

**Comment by TheMuntu** [comment]
> Well sounds like its a DNS issue. But regardless I think you should be able to use an IP address for the -l parameter

Still, -d/--domain parameter will be required.

**Comment by TheMuntu** [comment]
> Well sounds like its a DNS issue. But regardless I think you should be able to use an IP address for the -l parameter

Thank you for your support. It solved my issue 😸
